## © 2022 Nephio Authors
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0

---
- name: ensure tree is installed
  become: true
  ansible.builtin.package:
    name: tree
