## © 2022 Nephio Authors
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0
---
- name: Copy cluster config template
  template:
    src: "{{ role_path }}/templates/cluster-config.yaml.j2"
    dest: "{{ tmp_directory }}/{{ item.key }}-cluster-config.yaml"
    mode: 0644
  tags:
    - create

- name: Add extra port mapping for mgmt cluster ingress
  shell: |
    cat <<EOF >> {{ tmp_directory }}/{{ item.key }}-cluster-config.yaml
        kubeadmConfigPatches:
        - |
          kind: InitConfiguration
          nodeRegistration:
            kubeletExtraArgs:
              node-labels: "ingress-ready=true"
        extraPortMappings:
        - containerPort: 80
          hostPort: 7007
          protocol: TCP
    EOF
  when: item.key == "mgmt"

- name: Deploy cluster {{ item.key }} 
  shell: "kind create cluster --name {{ item.key }} --kubeconfig ~/.kube/{{ item.key }}-config --config /tmp/{{ item.key }}-cluster-config.yaml"
  register: result
  failed_when:
    - result.rc > 1
    - result.rc == 1 and "already exists" not in result.stderr
